trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 1. Build du projet Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# 2. Déploiement sur Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ClassRoom Connection'  # Remplace avec le nom de ta connexion Azure dans Azure DevOps
    appName: 'ClassRoomApp'  # Remplace par le nom de ton App Service
    package: '$(System.DefaultWorkingDirectory)/**/*.war'  # Assure-toi que le fichier .war est généré
