trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build_Java
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'

- stage: Deploy
  jobs:
  - job: Deploy_To_VM
    steps:
    - script: |
        ssh azureuser@VM_IP_PUBLIC "
          sudo apt-get update
          sudo apt-get install docker.io -y
          docker run -d --name prometheus -p 9090:9090 -v /home/azureuser/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
          docker run -d --name mon-app -p 8080:8080 myapp-image:latest
        "
      displayName: 'Deploy Prometheus and App to Azure VM'
